# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: go build ./apw
  displayName: 'Building apw'
# - script:
#     cd ./archive
#     go get -d
#     go build
#     cd ..
#   displayName: 'Building Archive Helper'
- script:
    cd ./compiler
    go get -d
    env GOOS=windows GOARCH=amd64 go build
    cd ..
  displayName: 'Building Compiler Helper'
- script:
    cd ./ftp
    go get -d
    go build
    cd ..
  displayName: 'Building FTP Helper'
- script:
    cd ./studio
    go get -d
    env GOOS=windows GOARCH=amd64 go build 
    cd ..
  displayName: 'Building Studio Helper'
